#!/usr/bin/env python3
"""Generate config.js from a BeReal data export."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REQUIRED_FILES = ("memories.json", "posts.json", "user.json")


def looks_like_export(path: Path) -> bool:
    return path.is_dir() and all((path / name).is_file() for name in REQUIRED_FILES)


def find_exports(root: Path) -> list[Path]:
    hits: list[Path] = []
    if looks_like_export(root):
        hits.append(root)
    for child in sorted(root.iterdir()):
        if child.name.startswith(".") or child.name in {"Photos", "node_modules"}:
            continue
        if looks_like_export(child):
            hits.append(child)
    data = root / "data"
    if data.is_dir() and looks_like_export(data) and data not in hits:
        hits.append(data)
    return hits


def extract_user_id(export: Path) -> str:
    user = json.loads((export / "user.json").read_text(encoding="utf-8"))
    profile = (user.get("profilePicture") or {}).get("path") or ""
    m = re.search(r"Photos/([^/]+)/", profile)
    if m:
        return m.group(1)

    memories = json.loads((export / "memories.json").read_text(encoding="utf-8"))
    if memories:
        front = (memories[0].get("frontImage") or {}).get("path") or ""
        m = re.search(r"Photos/([^/]+)/", front)
        if m:
            return m.group(1)

    # Folder names are usually "{userId}-{random}"
    name = export.name
    if "-" in name and len(name.split("-", 1)[0]) > 10:
        return name.split("-", 1)[0]

    raise SystemExit(
        f"Could not determine user id from {export}. "
        "Pass --user-id explicitly."
    )


def conversation_ids(export: Path) -> list[str]:
    conv_root = export / "conversations"
    if not conv_root.is_dir():
        return []
    ids = []
    for child in sorted(conv_root.iterdir()):
        if child.is_dir() and (child / "chat_log.json").is_file():
            ids.append(child.name)
    return ids


def write_config(
    out: Path,
    *,
    data_dir: str,
    user_id: str,
    conversations: list[str],
) -> None:
    payload = {
        "dataDir": data_dir,
        "userId": user_id,
        "conversationIds": conversations,
    }
    body = (
        "/* Generated by setup.py — do not commit (contains your export path / ids). */\n"
        "window.BEREAL_CONFIG = "
        + json.dumps(payload, indent=2)
        + ";\n"
    )
    out.write_text(body, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Point bereal-memories at your BeReal export and write config.js",
    )
    parser.add_argument(
        "export",
        nargs="?",
        help="Path to unzipped BeReal export folder (contains memories.json)",
    )
    parser.add_argument(
        "--user-id",
        help="Override detected BeReal user id",
    )
    parser.add_argument(
        "--out",
        default="config.js",
        help="Output path for config.js (default: ./config.js)",
    )
    args = parser.parse_args()

    root = Path.cwd()
    if args.export:
        export = Path(args.export).expanduser().resolve()
        if not looks_like_export(export):
            raise SystemExit(
                f"{export} does not look like a BeReal export "
                f"(expected {', '.join(REQUIRED_FILES)})"
            )
    else:
        candidates = find_exports(root)
        if not candidates:
            raise SystemExit(
                "No BeReal export found.\n"
                "Unzip your export into ./data/ (or pass the folder path):\n"
                "  python3 setup.py /path/to/your-export"
            )
        if len(candidates) > 1:
            print("Multiple exports found:")
            for i, c in enumerate(candidates, 1):
                try:
                    label = c.relative_to(root)
                except ValueError:
                    label = c
                print(f"  {i}. {label}")
            raise SystemExit("Pass one of these paths explicitly.")
        export = candidates[0]

    user_id = args.user_id or extract_user_id(export)
    conv_ids = conversation_ids(export)

    try:
        data_dir = str(export.relative_to(root)).replace("\\", "/")
    except ValueError:
        data_dir = str(export)

    out = Path(args.out)
    write_config(
        out,
        data_dir=data_dir,
        user_id=user_id,
        conversations=conv_ids,
    )

    print(f"Wrote {out}")
    print(f"  dataDir:          {data_dir}")
    print(f"  userId:           {user_id}")
    print(f"  conversations:    {len(conv_ids)}")
    print()
    print("Next:")
    print("  python3 -m http.server 8000")
    print("  open http://localhost:8000")
    return 0


if __name__ == "__main__":
    sys.exit(main())
